version: "3"
services:
  nodejs:
    build: client
    env_file:
      - ".env"
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - "PORT=3000"
    ports:
      - "$PORT:3000"

volumes:
  database:
    driver: local