# Generated by Django 3.2.5 on 2021-07-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profile',
            new_name='writer',
        ),
    ]
