# Generated by Django 3.2.5 on 2021-07-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_profile_comment_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='profile',
            new_name='writer',
        ),
    ]
