# Generated by Django 3.2.5 on 2021-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_profile_article_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='screen_name',
            field=models.CharField(default='noname', max_length=12, unique=True, verbose_name='スクリーンネーム'),
        ),
    ]
