# Generated by Django 3.2.5 on 2021-11-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
    ]
