# Generated by Django 3.2.5 on 2021-11-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20211120_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stocks',
            field=models.ManyToManyField(related_name='stocked_users', to='stock.Article', verbose_name='ストック記事'),
        ),
    ]
