# Generated by Django 3.2.5 on 2021-11-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_iniad_member',
            field=models.BooleanField(default=False, verbose_name='INIAD学内者か'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_toyo_member',
            field=models.BooleanField(default=False, verbose_name='東洋大学内者か'),
        ),
    ]
